# Generated by Django 5.1.1 on 2024-10-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_upload',
            field=models.FileField(blank=True, null=True, upload_to='course_content/'),
        ),
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
