# Generated by Django 5.1.1 on 2024-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0002_course_content_upload_course_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(),
        ),
    ]
