# Generated by Django 5.1.1 on 2024-10-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0004_file_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_files',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
