# Generated by Django 5.1.1 on 2024-10-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0006_course_buyers_course_cart_users_course_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart_courses',
            field=models.ManyToManyField(blank=True, related_name='cart_courses', to='eLearningApp.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_courses',
            field=models.ManyToManyField(blank=True, related_name='liked_courses', to='eLearningApp.course'),
        ),
    ]
