# Generated by Django 5.1.1 on 2024-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0007_profile_cart_courses_profile_liked_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_courses',
            field=models.ManyToManyField(blank=True, to='eLearningApp.course'),
        ),
    ]
