# Generated by Django 5.1.1 on 2024-10-15 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0008_alter_profile_liked_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='buyers',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
